{
 "title": "ping",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "lan_ips", "query": "(192.168.*)" }
  ]
 },
 "panels": [
  {
   "title": "Network Status Summary",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(job) (avg_over_time(probe_success{instance=~\"$lan_ips\"}[30s]))",
     "legendFormat": "LAN"
    },
    {
     "expr": "avg by(job) (avg_over_time(probe_success{instance!~\"$lan_ips\"}[30s]))",
     "legendFormat": "WAN"
    }
   ]
  },
  {
   "title": "LAN hosts",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$lan_ips\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Packet Loss 1m Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by(job) (avg_over_time(probe_success{instance=~\"$lan_ips\"}[1m]))",
     "legendFormat": "LAN"
    },
    {
     "expr": "1 - avg by(job) (avg_over_time(probe_success{instance!~\"$lan_ips\"}[1m]))",
     "legendFormat": "WAN"
    }
   ]
  },
  {
   "title": "WAN hosts",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{instance!~\"$lan_ips\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency (Round Trip Time)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\"} != 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Lookup Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_dns_lookup_time_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}